name: 🚨 Commitlint

on:
  pull_request:
    branches: ["develop"]
    types:
      - opened
      - edited

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code (mandatory step to access your repo)
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js (optional if you're certain the runner already has a compatible version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install dependencies with pnpm
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Create a Commitlint configuration
      - name: Setup Commitlint configuration
        run: |
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

      # Run Commitlint to verify PR title
      - name: Check PR title with Commitlint
        run: |
          echo "${{ github.event.pull_request.title }}" | pnpm exec commitlint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
